//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.2.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.example.androidannotationtesttwo.fragment;

import android.os.Bundle;
import android.support.v4.view.ViewPager;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import com.example.androidannotationtesttwo.R.layout;
import com.example.androidannotationtesttwo.widget.ColumnHorizontalScrollView;
import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class Fragment_home_
    extends com.example.androidannotationtesttwo.fragment.Fragment_home
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragmetn_home, container, false);
        }
        return contentView_;
    }

    @Override
    public void onDestroyView() {
        contentView_ = null;
        super.onDestroyView();
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        init();
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static Fragment_home_.FragmentBuilder_ builder() {
        return new Fragment_home_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        rl_column = ((RelativeLayout) hasViews.findViewById(com.example.androidannotationtesttwo.R.id.rl_column));
        button_more_columns = ((ImageView) hasViews.findViewById(com.example.androidannotationtesttwo.R.id.button_more_columns));
        mRadioGroup_content = ((LinearLayout) hasViews.findViewById(com.example.androidannotationtesttwo.R.id.mRadioGroup_content));
        shade_left = ((ImageView) hasViews.findViewById(com.example.androidannotationtesttwo.R.id.shade_left));
        top_more = ((ImageView) hasViews.findViewById(com.example.androidannotationtesttwo.R.id.top_more));
        mColumnHorizontalScrollView = ((ColumnHorizontalScrollView) hasViews.findViewById(com.example.androidannotationtesttwo.R.id.mColumnHorizontalScrollView));
        top_head = ((ImageView) hasViews.findViewById(com.example.androidannotationtesttwo.R.id.top_head));
        shade_right = ((ImageView) hasViews.findViewById(com.example.androidannotationtesttwo.R.id.shade_right));
        mViewPager = ((ViewPager) hasViews.findViewById(com.example.androidannotationtesttwo.R.id.mViewPager));
        ll_more_columns = ((LinearLayout) hasViews.findViewById(com.example.androidannotationtesttwo.R.id.ll_more_columns));
        if (button_more_columns!= null) {
            button_more_columns.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    Fragment_home_.this.onMoreColumns(view);
                }

            }
            );
        }
        if (top_head!= null) {
            top_head.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    Fragment_home_.this.onMenu(view);
                }

            }
            );
        }
        if (top_more!= null) {
            top_more.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    Fragment_home_.this.onAcount(view);
                }

            }
            );
        }
        initView();
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<Fragment_home_.FragmentBuilder_, com.example.androidannotationtesttwo.fragment.Fragment_home>
    {


        @Override
        public com.example.androidannotationtesttwo.fragment.Fragment_home build() {
            Fragment_home_ fragment_ = new Fragment_home_();
            fragment_.setArguments(args);
            return fragment_;
        }

    }

}
