//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.2.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.example.androidannotationtesttwo.adapter;

import android.content.Context;

public final class PhotoDetailAdapter_
    extends PhotoDetailAdapter
{

    private Context context_;

    private PhotoDetailAdapter_(Context context) {
        context_ = context;
        init_();
    }

    public static PhotoDetailAdapter_ getInstance_(Context context) {
        return new PhotoDetailAdapter_(context);
    }

    private void init_() {
        context = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
